file_format: "1"
id: totemm
name: TOTEMM
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - totem_left
  - totem_right
  - totem_dongle
